import { Link } from "wouter";
import { ArrowRight, CalendarDays, Calculator, CircleDollarSign, Search, ShieldCheck, Wrench } from "lucide-react";

type Intent = "fix" | "calculate" | "decide" | "when" | "cost";
const data: Record<Intent, {title:string; intro:string; examples:string[]; icon:any}> = {
 fix:{title:"Find the likely cause. Take the next step.",intro:"Describe what went wrong in plain English. Start with the simplest safe checks before you spend money.",examples:["My phone won't charge","My dryer is not heating","My car is making a clicking noise"],icon:Wrench},
 calculate:{title:"Put the numbers in. Get a useful answer.",intro:"Focused calculators for money, math, dates, health, home projects, and everyday decisions.",examples:["Mortgage payment","Percentage change","Tip and tax","Days between dates"],icon:Calculator},
 decide:{title:"Know what makes sense before you act.",intro:"Turn uncertain questions into clear conditions, tradeoffs, and next actions.",examples:["Can I freeze this food?","Can I paint over this surface?","Should I repair or replace it?"],icon:ShieldCheck},
 when:{title:"Get the date, deadline, or timing.",intro:"Find deadlines, countdowns, schedules, holidays, and useful timing windows.",examples:["How many days until a date?","When is the next holiday?","What date is 90 days from now?"],icon:CalendarDays},
 cost:{title:"Estimate the cost before you commit.",intro:"Understand price ranges, what changes the estimate, and when repair or replacement makes more sense.",examples:["How much does brake repair cost?","How much does a roof repair cost?","Repair vs. replace"],icon:CircleDollarSign}
};
const nav:Intent[]=["fix","calculate","decide","when","cost"];
export default function IntentPage({type}:{type:Intent}){const d=data[type],Icon=d.icon;return <main className="page-shell"><header className="site-header"><Link href="/" className="brand"><span className="brand-mark">V</span><span>vorqena</span></Link><nav className="desktop-nav">{nav.map(k=><Link className={k===type?"active":""} key={k} href={'/'+k}>{k[0].toUpperCase()+k.slice(1)}</Link>)}</nav><Link href="/" className="header-cta">Ask Vorqena <ArrowRight size={15}/></Link></header><section className="intent-hero"><div className="intent-hero-copy"><div className="eyebrow"><Icon size={16}/> {type}</div><h1>{d.title}</h1><p>{d.intro}</p><div className="search-box"><Search size={20}/><input aria-label={'Search '+type+' answers'} placeholder={'What do you need to '+type+'?'}/><kbd>⌘ K</kbd></div></div></section><section className="content-wrap"><div className="section-heading"><div><span className="eyebrow">Start with a question</span><h2>Try one of these</h2></div><span className="muted">Plain language works best.</span></div><div className="example-grid">{d.examples.map(x=><button className="example-card" key={x}>{x}<ArrowRight size={18}/></button>)}</div><div className="answer-framework"><div><span className="eyebrow">Answer-first</span><h2>Useful before exhaustive.</h2><p>Vorqena puts the practical answer first, then shows reasoning, assumptions, evidence, sources, and related questions when they help.</p></div><div className="framework-list"><div><b>01</b><span><strong>Answer</strong>What is most likely true?</span></div><div><b>02</b><span><strong>Evidence</strong>What supports it?</span></div><div><b>03</b><span><strong>Action</strong>What should you do next?</span></div></div></div><div className="related-intents"><span className="eyebrow">Keep going</span><h2>Related ways to solve it</h2><div className="related-grid">{nav.filter(k=>k!==type).map(k=><Link key={k} href={'/'+k}><span>{k[0].toUpperCase()+k.slice(1)}</span><small>{data[k].intro}</small><ArrowRight size={16}/></Link>)}</div></div></section><footer className="site-footer"><Link href="/" className="brand"><span className="brand-mark">V</span><span>vorqena</span></Link><span>Everyday answers, tools & decisions.</span><span>© 2026</span></footer></main>}
