import { Link, useParams } from "wouter";
import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Calculator, CheckCircle2, Search } from "lucide-react";
import { tools } from "../data/vorqena";

function Field({label, value, setValue, prefix, suffix}: any){return <label className="field"><span>{label}</span><div className="field-input">{prefix && <b>{prefix}</b>}<input type="number" value={value} onChange={e=>setValue(e.target.value)} />{suffix && <b>{suffix}</b>}</div></label>}

export default function ToolPage(){
 const {slug=""}=useParams(); const tool=tools.find(t=>t.slug===slug); const [a,setA]=useState("100"); const [b,setB]=useState("20"); const [c,setC]=useState("15");
 const result=useMemo(()=>{const x=Number(a)||0,y=Number(b)||0,z=Number(c)||0;
  switch(slug){case "percentage-calculator": return `${((x*y)/100).toFixed(2)}`;case "tip-calculator": return `$${(x+(x*y/100)).toFixed(2)} total`;case "loan-payment": {const r=y/100/12,n=z*12; return r?`$${(x*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1)).toFixed(2)} / month`:`$${(x/n).toFixed(2)} / month`;}case "fuel-cost": return `$${(x/(y||1)*z).toFixed(2)}`;case "electricity-cost": return `$${(x*y*z/1000).toFixed(2)}`;default:return `${((x*y)/100).toFixed(2)}`;}},[a,b,c,slug]);
 if(!tool)return <main className="page-shell"><header className="site-header"><Link href="/" className="brand"><span className="brand-mark">V</span><span>Vorqena</span></Link></header><section className="search-page"><h1>Tool not found</h1><Link href="/search">Search Vorqena <ArrowRight/></Link></section></main>;
 const isCalc=tool.intent==="calculate"||tool.intent==="cost"; return <main className="page-shell"><header className="site-header"><Link href="/" className="brand"><span className="brand-mark">V</span><span>Vorqena</span></Link><nav className="desktop-nav"><Link href="/fix">Fix</Link><Link href="/calculate">Calculate</Link><Link href="/decide">Decide</Link><Link href="/when">When</Link><Link href="/cost">Cost</Link></nav><Link href="/search" className="header-cta"><Search size={15}/> Search</Link></header><section className="tool-layout"><div className="tool-copy"><Link href={`/${tool.intent}`} className="back-link"><ArrowLeft size={15}/> {tool.intent}</Link><span className="eyebrow">Vorqena tool</span><h1>{tool.title}</h1><p>{tool.description}</p><div className="answer-card"><span className="answer-label">Your answer</span><strong>{isCalc ? result : "Start with the safest simple check."}</strong>{isCalc ? <span>Based on the numbers you entered.</span> : <span>Describe the symptoms in search to get a guided path.</span>}</div></div>{isCalc ? <div className="tool-card"><div className="tool-card-head"><Calculator/><h2>Calculator</h2></div><Field label={slug==="tip-calculator"?"Bill amount":"Value"} value={a} setValue={setA} prefix="$"/><Field label={slug==="fuel-cost"?"Efficiency":"Rate / percentage"} value={b} setValue={setB} suffix={slug==="fuel-cost"?"mi/gal":"%"}/><Field label={slug==="fuel-cost"?"Fuel price":"Amount / term"} value={c} setValue={setC} prefix={slug==="fuel-cost"?"$":""}/><div className="live-result"><CheckCircle2 size={18}/><div><span>Result</span><strong>{result}</strong></div></div></div> : <div className="tool-card"><div className="tool-card-head"><CheckCircle2/><h2>Quick checks</h2></div><div className="check-list"><p>1. Stop if there is smoke, burning smell, exposed wiring, leaking fluid, or another immediate hazard.</p><p>2. Check the obvious cause: power, connection, settings, blockage, or recent change.</p><p>3. If the simple checks fail, use the symptom details to narrow the cause before spending money.</p></div></div>}</section><section className="content-wrap tool-bottom"><h2>How Vorqena approaches this</h2><div className="principle-grid"><div><b>01</b><strong>Clear inputs</strong><span>Only ask for information that changes the result.</span></div><div><b>02</b><strong>Visible assumptions</strong><span>You can see what the answer depends on.</span></div><div><b>03</b><strong>Next action</strong><span>The result tells you what to do next.</span></div></div></section><footer className="site-footer"><span>Vorqena — Everyday answers, tools & decisions.</span><span>© 2026</span></footer></main>}
